var Res={
            business1 : '选择岗位',
            business2 : '选择培训需求调查',
            business3 : '下载文件',
            business4 : '选择菜单',
            business5 : '选择部门',
            business6 : '选择用户',
            business7 : '选择教室',
            business8 : '选择实践项目',
            business10 : '选择会议室',
            business11 : '选择考试',
            business12 : '选择练习',
            business13 : '选择培训机构',
            business14 : '选择证书项目',
            business15 : '选择讲师',
            business16 : '选择物品',
            business17 : '选择课程',
            business18 : '选择项目',
            business19 : '选择学习课程',
            business20 : '选择培训项目',
            business21 : '没有内容可导！',
            business22 : '无法调用Office对象，请确保您的机器已安装了Office并已将本系统的站点名加入到IE的信任站点列表中！',
            business23 : '特殊字符中任意三个组合',
            business24 : '访问数据库出错!',
            business25 : '网络链接失败,请检查您的网络状况再尝试!',
            business26 : '出现未知错误,请咨询管理员之后再尝试!',
            business27 : '关闭',
            business28 : '选择培训项目',
            business29 : '选择讲师',
            business30 : '选择课程',
            business31 : '选择培训计划',
            business32 : '选择认证活动',
            business33 : '选择聘用单位',
            business34 : '选择账号规则',
            business35 : '选择密码规则',
            business36 : '选择模板',
            business37 : '选择商品',
            business38 : '请输入关键字',
            business39 : '课程信息',
            business40 : '专题列表',
            business41 : '测评列表',
            business42 : '课程列表',
            business43 : '供应商列表',
            business44 : '机构课程列表',
            business45 : '云课程中心',
            business46 : '高级搜索',
            business47 : '请选择上传图片！',
            business48 : '只能上传后缀名为（.JPEG|.JPG|.GIF|.BMP|.PNG|）的文件！',
            business49 : '正在上传图片。。。',
            business50 : '请输入您要反馈的信息！',
            business51: '感谢您提交的反馈！我们将在第一时间与您取得联系，针对您提交的问题和建议进行详细的分析，努力改善您对博思特教育科技产品和服务的使用体验。',
            business52 : '提交反馈信息失败，失败原因：',
            business53 : '连接服务器异常，请检查网络！',
            cloud1:'智慧云中心出现错误请联系管理员处理，错误信息为：',
            cloud2:'已选',
            cloud3:'选修审核流程',
            cloud4:'暂时无法加载页面信息，请稍后再试！',
            cloud5:'选修',
            cloud6:'预订失败：',
            cloud7:'已订',
            cloud8:'行业云出现错误请联系管理员处理，错误信息为：',
            cloud9:'主题列表',
            cloud10:'行业云',

            AntiExam1:'非法操作！否则超过一次系统将自动提交试卷！',
            AntiExam2:'警告!禁止使用Alt+Tab键切换窗口，否则答卷将自动提交！',
            AntiExam3:'不可以在考试中粘贴文本！',
            AntiExam4:'请在试卷红色虚线区域内操作！否则超过一次系统将自动提交试卷！',
            
            CheckIE1:'系统在检查可信任站点时要运行ActiveX控件,\n\r可能会弹出对话框是允许ActiveX控件与页面交互的确认对话框,\n\r请点击\"确定\"按钮,否则无法对其进行检查.',
            
            
            common1:'请输入数字类型！',
            common2:'请输入整型数字！',
            common3:'请输入非负整型数字！',
            common4:'请输入日期类型！',
            common5:'无法调用Office对象，请确保您的机器已安装了Office并已将本系统的站点名加入到IE的信任站点列表中！',
            common6:'导出失败！',
            common7:'开始时间不能大于结束时间',
            common8:'结束时间不能小于开始时间',
            common9:'HTML编辑器',
            common10:'请先选择一项！',
            common11:'数据有误，无法添加到列表框！',
            common12:'请至少选择一项！',
            common13:'请输入非负数字！',
            common14:'加载中...',
            common15:'请输入内容...',
            common16:'添加收信人(请选择用户,如:abc, 多个以;符号分隔)',
            common17:'请输入登录名',
            common18:'请输入用户编号',
            common19:'请输入姓名',
            common20:'用户已经存在，请重新选择！',
            common21:'此课程需要缴费后才能进行学习，请联系管理员！',
            common22:'课程未扫描成功 请联系管理员！',
            common23:'验证课程学习条件失败，请联系管理员！',
            common24:'您确定现在参加考试吗？',

            Hanger1:'非法操作！否则超过一次系统将自动提交试卷！',
            Hanger2:'如果超过两次点击Win键及Alt + Tab键页面将自动提交！',
            Hanger3:'警告!禁止使用Alt+Tab键切换窗口，否则答卷将自动提交！',
            Hanger4:'禁止使用特殊功能键！如果超过两次点击Win键及Alt + Tab键页面将自动提交！',
            Hanger5:'禁止使用特殊功能键！',
            Hanger6:'禁止拷贝试卷！',
            Hanger7:'禁止在考试过程中关闭窗口！',
            Hanger8:'禁止在考试过程中粘贴文本！',
            
            SaveAnswer1:'请先将此站点加入到信任站点,并使您的IE允许下载本站点的ActiveX控件后您才能正常参加考试!错误提示：',
            SaveAnswer2:'您的答卷已于:{0}点{1}分{2}秒保存成功。',
            SaveAnswer3:'请先将此站点加入到信任站点,并使您的IE允许下载本站点的ActiveX控件后您才能正常参加考试!',
            SaveAnswer4:'系统所需要的ActiveX控件没有正确安装，可能的原因是安装或运行过程中杀毒软件或防火墙禁止了此组件，请改变杀毒软件或防火墙的设置或关闭它后再重新下载自动配置工具安装!',
            SaveAnswer5:'请先将此站点加入到信任站点,并使您的IE允许下载本站点的ActiveX控件后您才能正常参加考试!',
            
            Examining1:'考试出现异常！试卷格式不对．',
            Examining2:'考试出现异常！试卷模板找不到或格式有误,请联系考试管理员正确配置好系统.',
            Examining3:'保存答卷时出错',
            Examining4:'回答正确的试题分数是:{0}分，回答错误的试题应扣分是:{1}分，不回答的试题应扣分是:{2}分。',
            Examining5:'加密密匙只能是8位的数字。',
            Examining6:'您已经做过这题打字题,不可以重复做！',
            Examining7:'解析数据出错：',
            Examining8:'请稍后...',
            Examining9:'正在初始化页面...',
            Examining10:'初始化页面完成',
            Examining11:'初始化页面出错',
            Examining12:'[examUid]参数丢失，请重新参加！',
            Examining13:'正在加载考试信息数据...',
            Examining14:'加载考试信息数据完成',
            Examining15:'加载考试信息出错',
            Examining16:'服务器返回以下信息：{0} {1}。 请与系统管理员联系！',
            Examining17:'正在加载考试批次信息数据...',
            Examining18:'加载考试批次信息数据完成',
            Examining19:'加载考试批次信息出错',
            Examining20:'正在加载考生数据...',
            Examining21:'加载考生数据完成',
            Examining22:'加载考生数据失败',
            Examining23:'正在检查浏览器配置...',
            Examining24:'检查浏览器配置完成',
            Examining25:'出现错误',
            Examining26:'正在申请并初始化考试...',
            Examining27:'申请并初始化考试完成',
            Examining28:'获取初始化考试出错',
            Examining29:'正在加载试题页面，请稍后...',
            Examining30:'试题页面加载完成',
            Examining31:'获取始化试题页面出错',
            Examining32:'未发现试卷内容',
            Examining33:'试题检查',
            Examining34:'没做的试题有：',
            Examining35:'个,已在试题导航中显示，并且已有',
            Examining36:'个试题已做标注。',
            Examining37:'全部试题都已完成！',
            Examining38:'保存答卷时出错:',
            Examining39:'保存答案出错',
            Examining40:'关闭窗口',
            Examining41:'提交试卷出错',
            Examining42:'提示',
            Examining43:'结束闯关出错',
            Examining44:'下一关',
            Examining45:'结束闯关',
            Examining46:'查看答卷',
            Examining47:'测评报告',
            Examining48:'出现未知错误',
            Examining49:'执行操作[',
            Examining50:']失败，请与系统管理员联系！',
            Examining51:'关闭页面',
            Examining52:'如果超过2次点击组合键[Ctrl + Alt]或者[Ctrl + Alt+ Del]考卷将自动提交并结束本次考试！',
            Examining53:'误操作次数：',
            Examining54:'点击进入浏览器检测',
            Examining55:'浏览器检测失败',
            Examining56:'警告：系统检测到您启动了影响考试安全性的软件"',
            Examining57:'"，当前无法正常进行考试，请关闭相应程序后重新尝试!',

            Select1:'确定要删除该{0}吗？',
            Select2:'该{0}下存在记录，您确定要删除该{1}和它下面的所有的记录吗？',
            
            LessonStructPost1:'您确定要选中用户离{0}吗？',
            LessonStructPost2:' 您确定要删除选中课程体系的{0}记录吗？',
            LessonStructPost3:'{0}位详情',
            LessonStructPost4:'人员{0}位信息',
           
            JudgePaperScoreAlert:'提示：请输入有效的分数，允许分数范围[{0}]！',
            
            OnlineTrainPositionManage1:'您确定要创建[{0}]的{1}项目吗？',
            OnlineTrainPositionManage2:'您确定要按岗位体系中的课程设置创建选中{1}[{2}]的{3}项目吗？',
            
            Message4:'对不起,您输入的文本长度已超过系统最大限制,系统会自动栽剪超过范围的文本，继续吗！',
            Message1:'关闭',
            Message2:'确定',
            Message3:'取消',
            Message5:'请检查您与服务器的连接是否已经断开！',
            Message6:'操作出错，错误信息为：',
            
            OnlineLessonSafe1:'请先将此站点加入到信任站点,并使您的IE允许下载本站点的ActiveX控件后您才能正常学习此课件!',
            OnlineLessonSafe2:'系统所需要的ActiveX控件没有正确安装，可能的原因是安装或运行过程中杀毒软件或防火墙禁止了此组件，请改变杀毒软件或防火墙的设置或关闭它后再重新下载自动配置工具安装!',
            OnlineLessonSafe3:'请先将此站点加入到信任站点,并使您的IE允许下载本站点的ActiveX控件后您才能正常学习此课件!',

            LmsTrain1:'警告您无执行此操作的权限，请联系上级管理员提升您的权限级别！',
            LmsTrain2:'设置启动条件',
            LmsTrain3:'请在第一步中输入项目名称',
            LmsTrain4:'请先选择课程',
            LmsTrain5:'前置条件',
            LmsTrain6:'警告您无执行此操作的权限，请联系上级管理员提升您的权限级别！',
            LmsTrain7:'请先保存再添加考试！',
            LmsTrain8:'考试信息',
            LmsTrain9:'警告您无执行此操作的权限，请联系上级管理员提升您的权限级别！',
            LmsTrain10:'请先保存再添加作业！',
            LmsTrain11:'作业信息',
            LmsTrain12:'警告您无执行此操作的权限，请联系上级管理员提升您的权限级别！',
            LmsTrain13:'请先保存再添加练习！',
            LmsTrain14:'练习信息',
            LmsTrain15:'考试ID为空！',
            LmsTrain16:'警告您无执行此操作的权限，请联系上级管理员提升您的权限级别！',
            LmsTrain17:'考试信息',
            LmsTrain18:'试卷预览',
            LmsTrain19:'查看考生',
            LmsTrain20:'您确认要删除当前练习吗？',
            LmsTrain21:'您确认要删除当前考试吗？',
            LmsTrain22:'请在第一步中输入项目编号！',
            LmsTrain23:'请选择所属分类！',
            LmsTrain24:'项目名称不允许超过100个字符！',
            LmsTrain25:'截止时间不能大于开始时间！',
            LmsTrain26:'您是否要取消此次学习安排？',
            LmsTrain27:'您还没有添加课程，是否要结束此次学习安排？',
            LmsTrain28:'您还没有添加学员，是否要结束此次学习安排？',
            LmsTrain29:'您确认要删除当前课程吗？',
            LmsTrain30:'导入学员',
            LmsTrain31:'您确定要删除该部门吗？',
            LmsTrain32:'提示请先保存之后再进行此操作！',
            LmsTrain33:'请保存项目之后再上传图片!',
            LmsTrain34:'请选择要上传的文件！',
            LmsTrain35:'请选择正确的文件上传！',
            LmsTrain36:'选择课程图片',
            LmsTrain37:'添加图片',
            LmsTrain38:'更多课程选项展开+',
            LmsTrain39:'隐藏课程选项-',
            LmsTrain40:'点击选择课程',
            LmsTrain41:'点击设置前置条件',
            LmsTrain42:'0及为空表示不限制',
            LmsTrain43:'点击选择版主',
            LmsTrain44:'警告：系统检测到您启动了影响正常学习的软件"',
            LmsTrain45:'"，请关闭相应程序后重新尝试!',
            LmsTrain46:'请选择记录！',
            LmsTrain47:'批量修改课程',

            Bbs1:'已经超过了限定输入字符数..',
            Bbs2:'数据加载中，请稍等..',
            Bbs3:'没有更多数据了..',
            Bbs4:'更多>>',
            Bbs5:'获取数据失败，请检查网络后重试..',
            Bbs6:'您还没有发帖记录。。',
            Bbs7:'说点儿什么吧....',
            Bbs8:'您确定要删除该条帖子么？',
            Bbs9:'删除数据出现异常,请检查网络重试',
            Bbs10:'回复中。。',
            Bbs11:'回复',
            Bbs12:'回帖出现异常，请重试',
            Bbs13:'回贴过程发生异常，请检查网络重试'

};

/**
 * @return {string}
 */
function Translate(key,arguments,defaultValue){
    var message="";
    try{
        message = eval("Res."+key);
        if(message==null || typeof(message)=='undefined'){
			message = defaultValue;
		}
    }
    catch(e){
        message = defaultValue;
    }
    message=fillArgs(message,arguments);
    return message;
}

function fillArgs(message,arguments){
    var formated = message;
    for (i=0; i<arguments.length; i++)
    {
        var param = "\{"+i+"\}";  
        formated = formated.replace(param,arguments[i]);
    }
    return formated;
}